### ISSUE TITLE
Http request body 파싱 기능 구현 부탁드립니다.

### ISSUE THREAD

**Issue by juwkim** [world-famous-webserv/webserv#47]
http request header 출력 내용입니다.
http request body 내용은 코드를 본 결과 파싱하지 않고 있는 듯 합니다.
body 내용도 파싱이 된다면, POST 메소드 구현할 때 많이 도움이 되고,
cgi에 인자를 넘겨 줄 때도 필요합니다~
감사합니다.
![스크린샷 2023-12-05 오후 6 29 09](https://github.com/world-famous-webserv/webserv/assets/66457470/a20b0897-078a-4832-8785-00ed7393530f)

아래 내용에 헤더 부분 출력되는 것들이, body에 담겨있어야 합니다.
![스크린샷 2023-12-05 오후 6 41 21](https://github.com/world-famous-webserv/webserv/assets/66457470/ae3145ce-b45e-4d16-ad43-7e5401be60b9)

**Comment by iijung** [comment]
어떻게 쓰시는지 모르는 것 같아서 쉽게 수정했습니다. 

d23997ca69c4670e9b21811b8f056b6d9fe72a58
